### ISSUE TITLE
.pkl files

### ISSUE THREAD

**Issue by fhalamos** [Global-Policy-Lab/mosaiks-paper#2]
Hi! I'm wondering where can we download the .pkl files with the feature matrix. Thanks!

**Comment by bolliger32** [comment]
Hi @fhalamos ! Thanks for your interest in MOSAIKS. The easiest place to access these files is likely through our CodeOcean capusle: https://codeocean.com/capsule/6456296/tree/v2

See the data/int/feature_matrices directory

**Comment by fhalamos** [comment]
Amazing! Thanks a lot!
