### ISSUE TITLE
Code Capsule Run Failed

### ISSUE THREAD

**Issue by nilsleh** [Global-Policy-Lab/mosaiks-paper#3]
Hi, 
I am attempting to work/edit with the Code Capsule, however, when trying to launch any of the cloud workstations, the build fails with 
`Encountered problems while solving: - package nodejs-15.14.0-h92b4a50_0 requires icu >=68.1,<69.0a0, but none of the providers can be installed`

The complete buildLog can be found here.
[results-a4e81cfc-4604-40c1-885d-850e82d36839.zip](https://github.com/Global-Policy-Lab/mosaiks-paper/files/7862343/results-a4e81cfc-4604-40c1-885d-850e82d36839.zip)

**Comment by bolliger32** [comment]
Hi Nils,

I just double-checked using the published version of the capsule and the cloud workstation still loads fine. Is it possible you’ve modified the environment.yml file? Sorry I can’t be of more help.

**Comment by nilsleh** [comment]
I did not touch the environment.yml file. I have deleted and opened a new capsule from scratch, but the problem persists.

**Comment by bolliger32** [comment]
Sorry @nilsleh - not sure how to troubleshoot this as I cannot reproduce the error with a fresh clone of the capsule. My only other thought is to confirm that you are definitely cloning "v2" of the capsule (https://codeocean.com/capsule/6456296/tree/v2)? And have not changed the dockerfile either?

When I start up a cloud workstation I can confirm that I get the above-mentioned version of `nodejs` and I get `icu=68.1`. So it seems like something that was modified from the original capsule is now requiring `icu >= 69` which is causing a conflict. You could try adding `icu=68` to your environment file and see whether the conflicting package message becomes clearer. You could also try the `-v` flag added here: https://github.com/Global-Policy-Lab/mosaiks-paper/blob/14deccea3b7f67b34855870ac0807d83450225ba/environment/Dockerfile#L17.

**Comment by nilsleh** [comment]
Thanks @bolliger32, the "v2" was instead the error. When just making a new copy from this repo to code capsule it gets version 1 and not 2. It is working now. Thank you very much!
