### ISSUE TITLE
Availability of satellite imagery data

### ISSUE THREAD

**Issue by mjkleinman** [Global-Policy-Lab/mosaiks-paper#4]
I was looking through the codebase and data on CodeOcean and am wondering if the raw imagery data or a link to how they can be obtained is available? In the README it says that "we provide all of the pre-featurized images necessary to conduct our analysis within data/int/feature_matrices", but after loading the files, it looks like these correspond to the featurized images.

Thanks!

**Comment by salelkafrawy** [comment]
+1 
in the `1_create_rcf_feature_matrices.py` script there is a need for the images path which is in `data/raw/imagery` and the folder is not on CodeOcean

**Comment by bolliger32** [comment]
Hi @saraEbrahim and @mjkleinman. Unfortunately we're unable to share the raw images so that quote from the readme is correct - we can only share the featurized version of the images. "_Pre_-featurized" in this context refers to "before matching with labels and running a regression"

**Comment by salelkafrawy** [comment]
just to understand, the imagery that you can't share is the 1 x 1km tiles of the longitude and latitude of the 100k grid cells samples in the US for example?

**Comment by salelkafrawy** [comment]
and which satellite the images were from? or it would be great if there is a guide to use for our images

**Comment by bolliger32** [comment]
> just to understand, the imagery that you can't share is the 1 x 1km tiles of the longitude and latitude of the 100k grid cells samples in the US for example?

Correct.

> and which satellite the images were from? or it would be great if there is a guide to use for our images

The imagery comes from the Google Static Maps API (see Supplementary Note 1.2 for more details). Unfortunately, due to licensing constraints, we are unable to host and distribute these images.

**Comment by impnv** [comment]
Hi! I was trying to run the 1_create_rcf_feature_matrices.py on a self-developed dataset. In the process, I seem to have encountered 2 bugs in the code. 
1- In featurization.py line 414: file is opened with reading permission but right after the dill.dump is invoked to write in the file
2- In spatial.py line 118: pd.merge_asof is used but the lons dataframe is not sorted and it needs to be sorted.

Thanks!
