### ISSUE TITLE
Minor Bugs

### ISSUE THREAD

**Issue by impnv** [Global-Policy-Lab/mosaiks-paper#5]
Hi! I was trying to run the 1_create_rcf_feature_matrices.py on a self-developed dataset. In the process, I seem to have encountered 2 bugs in the code.
1- In featurization.py line 414: file is opened with reading permission but right after the dill.dump is invoked to write in the file
2- In spatial.py line 118: pd.merge_asof is used but the lons dataframe is not sorted and it needs to be sorted.

Thanks!

**Comment by bolliger32** [comment]
Thanks @impnv for your comments! 1 is indeed true. Fixing this with #6. For point 2, `Lons` should already be sorted as it would not make sense for the grid file to have an unsorted definition of x-axis longitude values. But I've added an assert statement to confirm

**Comment by impnv** [comment]
Ok @bolliger32 thank you! It was probably a problem I'm my definition of the grid.
